# -*- coding: utf-8 -*-
"""Lab1_cse22006.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsAv7ZmlVk8k_iVHGbJQ3YZ39Lf0WtrC
"""

def counts(input_string):
  vowel = "aeiouAEIOU"
  consonant = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"
  v=0
  c=0
  for ch in input_string:
    if ch in vowel:
      v=v+1
    if ch in consonant:
      c=c+1
  return v, c


input_string= input("Enter input string: ")
vowel_num, cons_num= counts(input_string)
print("Number of vowels in ", input_string, "is", vowel_num)
print("Number of consonants in ", input_string, "is", cons_num)

def count_elements(l1, l2):
  count = 0
  for e1 in l1:
    for e2 in l2:
      if e1 == e2:
        count += 1
        break
  return count
l1 = []
l2 = []
n1 = int(input("Enter the number of elements in 1st list: "))
for i in range(n1):
  e1 = int(input("Enter element: "))
  l1.append(e1)
n2 = int(input("Enter the number of elements in 2nd list: "))
for i in range(n2):
  e2 = int(input("Enter element: "))
  l2.append(e2)
common = count_elements(l1, l2)
print("Number of common elements:", common)